# values.yaml
replicaCount: 1
apps: file-upload
image:
  repository: file-upload-repo/file-upload
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: file-upload
  type: LoadBalancer
  port: 5000
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
configmap:
  enabled: true
secrets:
  enabled: true
  BUCKET_NAME: gcpconfig
  DATASET_ID: gcpconfig
  TABLE_ID: gcpconfig
  GOOGLE_APPLICATION_CREDENTIALS: serviceaccounttoken
