# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.BUCKET_NAME }}
                  key: BUCKET_NAME
            - name: DATASET_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.DATASET_ID }}
                  key: DATASET_ID
            - name: TABLE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.TABLE_ID }}
                  key: TABLE_ID
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.GOOGLE_APPLICATION_CREDENTIALS }}
                  key: GOOGLE_APPLICATION_CREDENTIALS
