# .github/workflows/build-and-test.yml

name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      DATASET_ID: ${{ vars.DATASET_ID }}
      TABLE_ID: ${{ vars.TABLE_ID }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Debug Google Credentials
      run: |
        echo "Credentials: $GOOGLE_APPLICATION_CREDENTIALS"

    - name: Run unit tests
      run: |
        pytest tests/

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY_FILE }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=default_credential_file.json" >> $GITHUB_ENV
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-image-name .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-image-name

