name: Deploy to GKE

on:
  workflow_dispatch: # This event triggers the workflow manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCP_RESOURCE_REGION: ${{ vars.GCP_RESOURCE_REGION }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_TAG: ${{ vars.IMAGE_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY_FILE }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials ${{ vars.GKE_CLUSTER }} --zone ${{ vars.GCP_RESOURCE_REGION }} --project ${GCP_PROJECT}
        gcloud components install kubectl

    - name: Deploy to GKE using Helm
      run: |
        helm upgrade --install \
          --namespace=default \
          --set image.repository=${{ vars.GCP_RESOURCE_REGION }}-docker.pkg.dev/$GCP_PROJECT/file-upload-repo/file-upload \
          --set image.tag=${IMAGE_TAG} \
          file-upload helm-charts/
    - name: Wait and Check Pod Status
      run: |
        sleep 60  # Adjust the sleep duration based on your deployment time
          
        POD_STATUS=$(kubectl get pod -l app=file-upload -o jsonpath='{.items[0].status.phase}')
          
        if [ "$POD_STATUS" != "Running" ]; then
          echo "Pod status is $POD_STATUS. Rolling back..."
          helm rollback --force file-upload  # Roll back to the previous revision
        else
          echo "Pod is running successfully."
        fi
